spring:
  application:
    name: service-warning
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/battery_warning_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group


dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://10.83.171.180:8848
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  provider:
    timeout: 5000
  config-center:
    enabled: false
server:
  port: 8084